Backport f2a32d996ae09620474771c46a649f6c4e1148ad
openjdk/jdk17u-dev pull request #1094
Opened 2023-01-20 16:54 UTC by lutkerd

Backporting followup fix to JDK-8287491

2023-01-25 17:22 UTC, lutkerd commented
/integrate

2023-01-25 18:20 UTC, phohensee reviewed
The patch looks like it includes more than just the original commit. Is there perhaps a predecessor backport that needs doing? Or perhaps the PR needs rebasing?

2023-01-25 18:23 UTC, lutkerd commented
I followed the instructions in this comment: https://github.com/openjdk/jdk17u-dev/pull/1094#issuecomment-1403990903 which say to merge master. Typically when going a rebase the bot complains and says not to do a rebase for a PR in flight. I think when the bot squashes this the extra code coming in from the merge of master should drop off as being already applied, but I am not 100% sure on that.

2023-01-25 18:31 UTC, phohensee reviewed
Ok. I'll wait for the pre-submit tests to finish and approve if all is well.

2023-01-25 23:11 UTC, phohensee requested changes
The pre-submit Windows build failures look to be unrelated.

The change to java.c is from https://bugs.openjdk.org/browse/JDK-8286694, and the change to Awt2dLibraries.gmk from https://bugs.openjdk.org/browse/JDK-8300692. Please remove these and backport them separately.

2023-01-25 23:18 UTC, lutkerd commented
Looks like other changes I was testing with GCC 12 also got pulled into that branch on merge. I've updated the PR to have a rebase on the master branch to clean up the extra commits that should be there.

2023-01-25 23:19 UTC, lutkerd commented
/integrate

2023-01-26 20:38 UTC, lutkerd commented
Failing pre-submit windows failures are due to the ongoing JTReg build issue.

2023-01-26 20:43 UTC, phohensee approved these changes
Lgtm.

2023-01-26 20:45 UTC, closed without merging