Backport 486f90c134f3b8562221839f8a3aefa74ae0d070
openjdk/jdk17u-dev pull request #1568
Opened 2023-07-11 11:48 UTC by GoeLin

I would like to backport this to 17 to make configure more stable.

I had to move the code to file loolchain. 
"[8292717: Clean up checking of testing requirements in configure](https://github.com/openjdk/jdk/commit/16593cf51c3d994ba4a6d28ab97e519dfd53f37b)" moves related code to lib-tests.m4.

2023-07-11 12:57 UTC, shipilev approved these changes
Looks good, thanks.

2023-07-11 12:59 UTC, shipilev requested changes
Actually not. The cross-compilation builds that do not set `--with-jtreg` are now failing.

2023-07-11 13:03 UTC, shipilev commented
Need this one as follow-up: https://github.com/openjdk/jdk/commit/d92e00a5191e8b50a5a17e3cd0105dbfb5a00281.

The bug was not linked to this one, linked up now.

2023-07-11 13:14 UTC, GoeLin commented
/issue JDK-8292716

2023-07-11 13:15 UTC, GoeLin commented
Aleksey, thanks for spotting this!

2023-07-11 13:35 UTC, shipilev commented
Should be `/issue add JDK-8292763`?

2023-07-11 14:09 UTC, GoeLin commented
/issue add JDK-8292763

Sure ... ;)

2023-07-11 14:13 UTC, shipilev approved these changes
Looks good, provided tests are passing.

2023-07-12 09:12 UTC, GoeLin commented
/integrate

2023-07-12 09:13 UTC, closed without merging