8284772: GHA: Use GCC Major Version Dependencies Only
openjdk/jdk17u-dev pull request #1673
Opened 2023-08-18 16:16 UTC by gnu-andrew

GHA regularly breaks because we specify a very explicit GCC version, even down to the release versioning of the Ubuntu package.

Rather than bumping this yet again like https://github.com/openjdk/jdk17u/commit/260f28761a87553fd634615df5ba3db5b76ae692, this PR suggests dropping the specific version as we did some time ago in 8u and I've also proposed to fix the same breakage in 11u (https://github.com/openjdk/jdk11u-dev/pull/2087). The requirement still specifies a specific major version of GCC. It just means the dependency isn't broken every time Ubuntu bumps to a new minor release or even just makes a minor change to the package alone.

Note that the current setup does not guarantee sticking with an exact version of GCC anyway, because - as seen by recent GHA breakage - older versions get removed from the package repository. All we get from this exact version requirement is sporadic breakage. If we truly want a static version of GCC, we need to provide our own as we do with the JDK.

~~This is based on https://github.com/openjdk/jdk17u-dev/pull/1595 to allow https://github.com/openjdk/jdk17u-dev/pull/1672 to proceed.~~ This is now based on master and the change is in trunk.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8284772](https://bugs.openjdk.org/browse/JDK-8284772): GHA: Use GCC Major Version Dependencies Only (**Bug** - P4)

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/1673/head:pull/1673` \
`$ git checkout pull/1673`

Update a local copy of the PR: \
`$ git checkout pull/1673` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/1673/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1673`

View PR using the GUI difftool: \
`$ git pr show -t 1673`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1673.diff">https://git.openjdk.org/jdk17u-dev/pull/1673.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/1673#issuecomment-1684151248)

2023-08-21 10:13 UTC, shipilev requested changes
Nope, not for 17u.

While the actual removal of minor GCC version tracking might be okay, it is wrong to keep effectively _forward-porting_ the GHA change from 8u -> 11u -> 17u. You need to do this in mainline, argue the point on minor GCC version removals (in other words, the reversal of [JDK-8256393](https://bugs.openjdk.org/browse/JDK-8256393)), and then argue for backports. Otherwise, you will keep doing this for every subsequent XXu.

2023-08-21 12:25 UTC, tstuefe commented
I'm very much in favor of dropping the GCC minor version dependency since it has been a huge pain. I don't care for patch direction, as long as we can convince mainline to do the same.

2023-08-22 02:20 UTC, gnu-andrew commented
> Nope, not for 17u.
> 
> While the actual removal of minor GCC version tracking might be okay, it is wrong to keep effectively _forward-porting_ the GHA change from 8u -> 11u -> 17u. You need to do this in mainline, argue the point on minor GCC version removals (in other words, the reversal of [JDK-8256393](https://bugs.openjdk.org/browse/JDK-8256393)), and then argue for backports. Otherwise, you will keep doing this for every subsequent XXu.

Yes, this was never intended to be merged in the current state anyway. It was provided so we could see if #1672 would actually fix the JTReg failures.

My intention was to propose it to trunk as well in due course and I've now done that (https://github.com/openjdk/jdk/pull/15374). We can still use this PR for the subsequent 17u PR. I would very much like to see someone argue in favour of keeping this versioning. It seems to have been added with little review and has baffled me from the start. I was surprised to find it was still present over this last week. I had hoped someone else would have ditched it long ago. I tend to be focused mostly on 8u, where we dropped it from the start and haven't had any problems since.

2023-08-22 02:22 UTC, gnu-andrew commented
> I'm very much in favor of dropping the GCC minor version dependency since it has been a huge pain. I don't care for patch direction, as long as we can convince mainline to do the same.

Hopefully. Having had tests fail three times in the last week due to this (once in 11u, once in 17u and once in our own fork of 21u), I'm surprised people have stuck with it this long.

2023-08-24 06:23 UTC, shipilev approved these changes
Looks okay now. I guess we should be doing these in every maintained release at this point.

2023-08-25 07:00 UTC, shipilev commented
@gnu-andrew, you need `jdk17u-fix-request` on it now, I think.

2023-08-28 12:33 UTC, gnu-andrew commented
> Looks okay now. I guess we should be doing these in every maintained release at this point.

Yes, I should open a PR for 21u. Added `jdk17u-fix-request` for this one now. Thanks for the review.

2023-08-29 02:27 UTC, gnu-andrew commented
I see `jdk17u-fix-yes`
/integrate

2023-08-29 02:29 UTC, closed without merging