Backport 6f76b65ace50b2361221dddab120e91b057497c1
openjdk/jdk17u-dev pull request #1735
Opened 2023-09-13 12:46 UTC by GoeLin

I backport this for parity with 17.0.10-oracle.

I had to resolve because of NULL/nulptr differences.

2023-09-13 20:14 UTC, phohensee requested changes
The test is missing, plus nullptr is used. Something went wrong. :)

2023-09-14 08:29 UTC, GoeLin commented
Hi Paul, thanks for spotting this.  I added the test.
Using nullptr is not an issue, it is used in many places in 17, it is only that the occurance of NULL spoils the patching.

2023-09-14 12:09 UTC, phohensee approved these changes
Looks good now.

2023-09-15 14:13 UTC, GoeLin commented
/integrate

2023-09-15 14:15 UTC, closed without merging