8300696: [AIX] AttachReturnError fails
openjdk/jdk17u-dev pull request #1896
Opened 2023-10-19 18:51 UTC by deepa181

This PR backports the change reported in [JDK-8300696](https://bugs.openjdk.org/browse/JDK-8300696).

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] [JDK-8300696](https://bugs.openjdk.org/browse/JDK-8300696) needs maintainer approval

### Issue
 * [JDK-8300696](https://bugs.openjdk.org/browse/JDK-8300696): [AIX] AttachReturnError fails (**Bug** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/1896/head:pull/1896` \
`$ git checkout pull/1896`

Update a local copy of the PR: \
`$ git checkout pull/1896` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/1896/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1896`

View PR using the GUI difftool: \
`$ git pr show -t 1896`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1896.diff">https://git.openjdk.org/jdk17u-dev/pull/1896.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/1896#issuecomment-1771547998)

2023-10-22 17:13 UTC, deepa181 commented
Hi @tstuefe , @dholmes-ora

I performed  tier test and builds both fastdebug and release on AIX and Linux. It works fine.
So, Could you please review this backport ?

I would appreciate your valuable input!

Thank You.

2023-10-23 05:28 UTC, tstuefe commented
Hi @deepa181, sure. For future backports, if the backport is not clean please give us a short sentence about what you had to change to make the patch fit, that saves us time having to compare the patch with the one in mainline.

2023-10-23 05:30 UTC, tstuefe requested changes
There is something wrong with this patch. Why are the linux parts in there?

2023-10-23 06:25 UTC, deepa181 commented
> Hi @deepa181, sure. For future backports, if the backport is not clean please give us a short sentence about what you had to change to make the patch fit, that saves us time having to compare the patch with the one in mainline.

Sure, I'll include brief change descriptions for future backports. Thanks for the suggestion!

2023-10-25 11:32 UTC, deepa181 commented
> There is something wrong with this patch. Why are the linux parts in there?

 I made changes to address a Linux-specific error encountered in the GHA check. The modification ensures that the l_path variable is correctly assigned to l_pathdup when it is not a null pointer, improving the code's behavior and resolving the error on the Linux platform and also not affecting on AIX.

2023-10-25 11:47 UTC, tstuefe commented
> > There is something wrong with this patch. Why are the linux parts in there?
> 
> I made changes to address a Linux-specific error encountered in the GHA check. The modification ensures that the l_path variable is correctly assigned to l_pathdup when it is not a null pointer, improving the code's behavior and resolving the error on the Linux platform and also not affecting on AIX.

No, please don't add in changes that have nothing to do with the bug title, especially not if the patch is supposed to be confined to a single platform and the change affects other platforms, and/or if the issue was fixed upstream with a different bug.

- If this is an upstream bug unfixed: fix there, downport fix
- If this is an upstream bug that has been fixed upstream: downport fix
- If this is a downstream-only issue (that is rare): fix downstream either with a separate bug id or as part of the originating bug

In this case you need to downport https://bugs.openjdk.org/browse/JDK-8297242 . If this patch relies on https://bugs.openjdk.org/browse/JDK-8297242, downport that one first, then this one.

2023-10-31 14:43 UTC, deepa181 commented
> > > There is something wrong with this patch. Why are the linux parts in there?
> > 
> > 
> > I made changes to address a Linux-specific error encountered in the GHA check. The modification ensures that the l_path variable is correctly assigned to l_pathdup when it is not a null pointer, improving the code's behavior and resolving the error on the Linux platform and also not affecting on AIX.
> 
> No, please don't add in changes that have nothing to do with the bug title, especially not if the patch mentions a single platform and the change affects other platforms, and/or if the issue was fixed upstream with a different bug.
> 
> * If this is an upstream bug unfixed: fix there, downport fix
> * If this is an upstream bug that has been fixed upstream: downport fix
> * If this is a downstream-only issue (that is rare): fix downstream either with a separate bug id or as part of the originating bug
> 
> In this case you need to downport https://bugs.openjdk.org/browse/JDK-8297242 . If this patch relies on https://bugs.openjdk.org/browse/JDK-8297242, downport that one first, then this one.

Okay. Thank You @tstuefe . Now I understood. I will follow the recommended approach:
* 		Downport the fix from https://bugs.openjdk.org/browse/JDK-8297242.
* 		Then, apply the changes to address the specific bug mentioned in the patch.
Thank you for the guidance.

2023-10-31 14:47 UTC, deepa181 commented
> > > There is something wrong with this patch. Why are the linux parts in there?
> > 
> > 
> > I made changes to address a Linux-specific error encountered in the GHA check. The modification ensures that the l_path variable is correctly assigned to l_pathdup when it is not a null pointer, improving the code's behavior and resolving the error on the Linux platform and also not affecting on AIX.
> 
> No, please don't add in changes that have nothing to do with the bug title, especially not if the patch mentions a single platform and the change affects other platforms, and/or if the issue was fixed upstream with a different bug.
> 
> * If this is an upstream bug unfixed: fix there, downport fix
> * If this is an upstream bug that has been fixed upstream: downport fix
> * If this is a downstream-only issue (that is rare): fix downstream either with a separate bug id or as part of the originating bug
> 
> In this case you need to downport https://bugs.openjdk.org/browse/JDK-8297242 . If this patch relies on https://bugs.openjdk.org/browse/JDK-8297242, downport that one first, then this one.

Thank you so much @tstuefe. Now I understood. I will follow the recommended approach.

2023-11-02 05:39 UTC, closed without merging