Backport 3e2314d08218dc8a4f4fc61bd4e1d5e58a0129c7
openjdk/jdk17u-dev pull request #2689
Opened 2024-07-08 14:52 UTC by gdams

Not a clean backport as there were white space conflicts and non existent `test/hotspot/gtest/code/test_codestrings.cpp file to be deleted`.

GHA tested.
Tier1/tier2 tests passed on linux

2024-07-08 15:24 UTC, MBaesken requested changes
test/hotspot/gtest/unittest.hpp
why did you remove
// A work around for GCC math header bug leaving isfinite() undefined,
// see: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=14608
#include "utilities/globalDefinitions.hpp"

I do not really see what this has to do with the attention of 8299254.
And
gtest_exit_from_child_vm
was added in the same file - is there some good reason for this ?
Do not see in the original commit https://github.com/openjdk/jdk/commit/3e2314d08218dc8a4f4fc61bd4e1d5e58a0129c7

2024-07-08 15:27 UTC, gdams commented
> test/hotspot/gtest/unittest.hpp why did you remove // A work around for GCC math header bug leaving isfinite() undefined, // see: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=14608 #include "utilities/globalDefinitions.hpp"
> 
> I do not really see what this has to do with the attention of 8299254. And gtest_exit_from_child_vm was added in the same file - is there some good reason for this ? Do not see in the original commit [openjdk/jdk@3e2314d](https://github.com/openjdk/jdk/commit/3e2314d08218dc8a4f4fc61bd4e1d5e58a0129c7)

good spot! thanks @MBaesken, I've fixed that now

2024-07-09 06:50 UTC, MBaesken approved these changes

2024-07-09 07:24 UTC, gdams commented
/approval request These changes don't apply cleanly but have had thorough testing to ensure no breaking changes have been introduced. This backport is essential to resolve the xcode14 build failures

2024-07-09 07:29 UTC, gdams commented
/integrate

2024-07-09 07:31 UTC, closed without merging