Backport c37988d0793b24d98d285530dfda69999a227937
openjdk/jdk17u-dev pull request #840
Opened 2022-10-25 22:24 UTC by asgibbons

This is a backport of JDK-8268276: Base64 Decoding optimization for x86 using AVX-512.

We have had numerous customer requests for this functionality to be backported due to the ~19x performance improvement.
 
Original patch does not apply cleanly to 17u, because of a bug that was identified in the original commit, but not fixed until the later Base64 Encode acceleration enhancement was complete.  The fix is on line 6039 of src/hotspot/cpu/x86/stubGenerator_x86_64.cpp and has been included in this PR.  All four "translatedX" registers needed to be checked for illegal characters in the input stream.

Risk: I view the risk of this backport to be minimal.  This code has been in use for many months with no bugs reported.
 
Testing: x86_64 build, affected tests, tier1, tier2
 
Thanks,
--Scott

2022-10-25 22:52 UTC, asgibbons commented
/label add hotspot

2022-10-28 20:37 UTC, dwhite-intel commented
Hi Scott,

Can you post the diff between this backport and the original JDK-8268276 patch? I'm guessing it's pretty small, but it will be good to see.

Thanks!
 - Derek

2022-10-28 23:57 UTC, asgibbons commented on src/hotspot/cpu/x86/stubGenerator_x86_64.cpp
> +      __ vpternlogd(input0, 0xfe, translated2, translated3, Assembler::AVX_512bit);
This line was changed from

      __ vpternlogd(input0, 0xfe, translated1, translated2, Assembler::AVX_512bit);

It was changed to:

      __ vpternlogd(input0, 0xfe, translated2, translated3, Assembler::AVX_512bit);

2022-11-01 17:02 UTC, asgibbons commented
@dwhite-intel Did I answer your question to your satisfaction?  I'd appreciate a review if you have time.  Thanks!

2022-11-01 21:06 UTC, asgibbons commented
So, the original patch applied cleanly, then I included the two bugfixes that were subsequently found (JDK-8273108 and JDK-8269404), one relating to improper illegal character discovery and the other relating to writing past end-of-string.

2022-11-01 22:03 UTC, dwhite-intel commented
This looks good to me. Still need a (R)eviewer.

2022-11-01 22:26 UTC, phohensee requested changes
Looks like you didn't backport the change to .gitignore. Seems unrelated to the rest of the patch, but harmless enough.

Other than that, lgtm.

2022-11-01 23:53 UTC, asgibbons commented
Thanks, @phohensee .  This is an unneeded artifact of me using VS for editing.  I do not believe it affects anything.

2022-11-02 13:46 UTC, phohensee approved these changes
Yes, it doesn't affect anything, but might be a merge conflict down the line. Let's see what the approvers say. Lgtm.

2022-11-02 15:03 UTC, asgibbons commented
/contributor add drwhite

2022-11-02 19:49 UTC, asgibbons commented
/contributor add sviswanathan

2022-11-02 19:51 UTC, asgibbons commented
/integrate defer

2022-11-02 19:52 UTC, asgibbons commented
/integrate undefer
/integrate

2022-11-02 21:29 UTC, asgibbons commented
/integrate defer

2022-11-07 19:19 UTC, asgibbons commented
Trying to do dependent PRs instead of piecemealing.  Let me know if I'm doing something wrong.

2022-11-07 19:19 UTC, closed without merging